version: '3.8'

services:
  app:
    build: .
    container_name: GlassUI
    ports:
      - '3800:3000'
    environment:
      NODE_ENV: development
    volumes:
      - .:/src/usr/app
      - /src/usr/app/node_modules
